// T049: Dependency Reporting and Documentation Generation
// Main implementation for comprehensive dependency reporting, documentation generation, and export capabilities

#include "dependency_reporter.h"
#include <fstream>
#include <sstream>
#include <algorithm>
#include <iomanip>
#include <filesystem>
#include <random>
#include <regex>
#include <numeric>

namespace fs = std::filesystem;

namespace integration {

DependencyReporter::DependencyReporter(const std::string& cache_dir)
    : cache_dir_(cache_dir) {
    default_export_path_ = cache_dir + "/reports";
    initialized_ = initialize();
}

DependencyReporter::~DependencyReporter() = default;

bool DependencyReporter::initialize() {
    if (!ensureDirectoryExists(cache_dir_)) {
        return false;
    }

    if (!ensureDirectoryExists(default_export_path_)) {
        return false;
    }

    return loadDefaultTemplates();
}

DependencyReport DependencyReporter::generateDependencyReport(const std::vector<DependencyInfo>& dependencies) const {
    DependencyReport report;
    report.report_id = generateReportID();
    report.generated_timestamp = getCurrentTimestamp();
    report.generated_by = "DependencyReporter v1.0.0";
    report.total_dependencies = static_cast<int>(dependencies.size());
    report.dependencies = dependencies;

    // Calculate statistics
    for (const auto& dep : dependencies) {
        if (dep.status == "active") {
            report.active_dependencies++;
        } else if (dep.status == "outdated") {
            report.outdated_dependencies++;
        }

        if (!dep.license.empty()) {
            report.license_types[dep.license]++;
        }

        if (!dep.source_type.empty()) {
            report.source_types[dep.source_type]++;
        }

        if (!dep.security_issues.empty()) {
            report.security_issues += static_cast<int>(dep.security_issues.size());
        }
    }

    // Generate recommendations
    report.recommendations = generateRecommendations(dependencies);

    // Add metadata
    report.metadata["generator_version"] = getReportVersion();
    report.metadata["os"] = "Linux";
    report.metadata["generation_time_ms"] = "0";

    return report;
}

json DependencyReporter::generateJSONReport(const std::vector<DependencyInfo>& dependencies) const {
    auto report = generateDependencyReport(dependencies);

    json json_report;
    json_report["report_id"] = report.report_id;
    json_report["generated_timestamp"] = report.generated_timestamp;
    json_report["generated_by"] = report.generated_by;
    json_report["total_dependencies"] = report.total_dependencies;
    json_report["active_dependencies"] = report.active_dependencies;
    json_report["outdated_dependencies"] = report.outdated_dependencies;
    json_report["security_issues"] = report.security_issues;
    json_report["license_types"] = report.license_types;
    json_report["source_types"] = report.source_types;
    json_report["recommendations"] = report.recommendations;
    json_report["metadata"] = report.metadata;

    // Add dependencies
    json deps_array = json::array();
    for (const auto& dep : dependencies) {
        deps_array.push_back(dependencyToJSON(dep));
    }
    json_report["dependencies"] = deps_array;

    return json_report;
}

std::string DependencyReporter::generateMarkdownReport(const std::vector<DependencyInfo>& dependencies) const {
    auto report = generateDependencyReport(dependencies);

    std::ostringstream markdown;

    markdown << "# Dependency Report\n\n";
    markdown << "**Report ID:** " << report.report_id << "\n";
    markdown << "**Generated:** " << report.generated_timestamp << "\n";
    markdown << "**Generated by:** " << report.generated_by << "\n\n";

    // Summary section
    markdown << "## Summary\n\n";
    markdown << "- **Total Dependencies:** " << report.total_dependencies << "\n";
    markdown << "- **Active Dependencies:** " << report.active_dependencies << "\n";
    markdown << "- **Outdated Dependencies:** " << report.outdated_dependencies << "\n";
    markdown << "- **Security Issues:** " << report.security_issues << "\n\n";

    // License types
    if (!report.license_types.empty()) {
        markdown << "### License Distribution\n\n";
        for (const auto& [license, count] : report.license_types) {
            markdown << "- **" << license << ":** " << count << "\n";
        }
        markdown << "\n";
    }

    // Source types
    if (!report.source_types.empty()) {
        markdown << "### Source Distribution\n\n";
        for (const auto& [source, count] : report.source_types) {
            markdown << "- **" << source << ":** " << count << "\n";
        }
        markdown << "\n";
    }

    // Dependencies table
    markdown << "## Dependencies\n\n";
    markdown << "| Name | Version | Status | License | Source | Compatibility |\n";
    markdown << "|------|---------|--------|---------|--------|---------------|\n";

    for (const auto& dep : dependencies) {
        markdown << "| " << dep.name
                 << " | " << dep.version
                 << " | " << dep.status
                 << " | " << dep.license
                 << " | " << dep.source_type
                 << " | " << formatCompatibilityScore(dep.compatibility_score)
                 << " |\n";
    }
    markdown << "\n";

    // Recommendations
    if (!report.recommendations.empty()) {
        markdown << "## Recommendations\n\n";
        for (size_t i = 0; i < report.recommendations.size(); ++i) {
            markdown << (i + 1) << ". " << report.recommendations[i] << "\n";
        }
        markdown << "\n";
    }

    return markdown.str();
}

std::string DependencyReporter::generateHTMLReport(const std::vector<DependencyInfo>& dependencies) const {
    auto report = generateDependencyReport(dependencies);

    std::ostringstream html;

    html << generateHTMLHeader("Dependency Report");

    html << "<body>\n";
    html << "<div class=\"container\">\n";

    // Header
    html << "<header>\n";
    html << "<h1>Dependency Report</h1>\n";
    html << "<div class=\"report-info\">\n";
    html << "<p><strong>Report ID:</strong> " << report.report_id << "</p>\n";
    html << "<p><strong>Generated:</strong> " << report.generated_timestamp << "</p>\n";
    html << "<p><strong>Generated by:</strong> " << report.generated_by << "</p>\n";
    html << "</div>\n";
    html << "</header>\n";

    // Summary section
    html << "<section class=\"summary\">\n";
    html << "<h2>Summary</h2>\n";
    html << "<div class=\"stats-grid\">\n";
    html << "<div class=\"stat-card\"><h3>" << report.total_dependencies << "</h3><p>Total Dependencies</p></div>\n";
    html << "<div class=\"stat-card\"><h3>" << report.active_dependencies << "</h3><p>Active Dependencies</p></div>\n";
    html << "<div class=\"stat-card\"><h3>" << report.outdated_dependencies << "</h3><p>Outdated Dependencies</p></div>\n";
    html << "<div class=\"stat-card\"><h3>" << report.security_issues << "</h3><p>Security Issues</p></div>\n";
    html << "</div>\n";
    html << "</section>\n";

    // Dependencies table
    html << "<section class=\"dependencies\">\n";
    html << "<h2>Dependencies</h2>\n";
    html << "<table class=\"dependency-table\">\n";
    html << "<thead>\n";
    html << "<tr><th>Name</th><th>Version</th><th>Status</th><th>License</th><th>Source</th><th>Compatibility</th></tr>\n";
    html << "</thead>\n";
    html << "<tbody>\n";

    for (const auto& dep : dependencies) {
        std::string status_class = dep.status == "active" ? "status-active" :
                                  dep.status == "outdated" ? "status-outdated" : "status-unknown";

        html << "<tr>\n";
        html << "<td>" << escapeHTML(dep.name) << "</td>\n";
        html << "<td>" << escapeHTML(dep.version) << "</td>\n";
        html << "<td class=\"" << status_class << "\">" << escapeHTML(dep.status) << "</td>\n";
        html << "<td>" << escapeHTML(dep.license) << "</td>\n";
        html << "<td>" << escapeHTML(dep.source_type) << "</td>\n";
        html << "<td>" << formatCompatibilityScore(dep.compatibility_score) << "</td>\n";
        html << "</tr>\n";
    }

    html << "</tbody>\n";
    html << "</table>\n";
    html << "</section>\n";

    // Recommendations
    if (!report.recommendations.empty()) {
        html << "<section class=\"recommendations\">\n";
        html << "<h2>Recommendations</h2>\n";
        html << "<ul class=\"recommendations-list\">\n";
        for (const auto& rec : report.recommendations) {
            html << "<li>" << escapeHTML(rec) << "</li>\n";
        }
        html << "</ul>\n";
        html << "</section>\n";
    }

    html << "</div>\n";
    html << "</body>\n";
    html << "</html>\n";

    return html.str();
}

std::string DependencyReporter::generateCSVReport(const std::vector<DependencyInfo>& dependencies) const {
    std::ostringstream csv;

    // Header
    csv << "Name,Version,Status,License,Source,Compatibility Score,Description,URL,SHA256,Last Update\n";

    // Data rows
    for (const auto& dep : dependencies) {
        csv << "\"" << dep.name << "\","
            << "\"" << dep.version << "\","
            << "\"" << dep.status << "\","
            << "\"" << dep.license << "\","
            << "\"" << dep.source_type << "\","
            << dep.compatibility_score << ","
            << "\"" << dep.description << "\","
            << "\"" << dep.url << "\","
            << "\"" << dep.sha256 << "\","
            << "\"" << dep.last_update << "\"\n";
    }

    return csv.str();
}

DependencyMetrics DependencyReporter::generateDependencyMetrics(const std::vector<DependencyInfo>& dependencies) const {
    DependencyMetrics metrics;
    metrics.total_dependencies = static_cast<int>(dependencies.size());

    std::vector<double> compatibility_scores;

    for (const auto& dep : dependencies) {
        if (dep.status == "active") {
            metrics.active_dependencies++;
        } else if (dep.status == "outdated") {
            metrics.outdated_dependencies++;
        }

        if (!dep.security_issues.empty()) {
            metrics.security_issues += static_cast<int>(dep.security_issues.size());
        }

        if (dep.compatibility_score > 0) {
            compatibility_scores.push_back(dep.compatibility_score);
        }

        // Track recent and old dependencies
        if (!dep.last_update.empty()) {
            if (metrics.most_recent_updates.size() < 5) {
                metrics.most_recent_updates.push_back(dep.name + " (" + dep.last_update + ")");
            }
        }
    }

    // Calculate average compatibility score
    if (!compatibility_scores.empty()) {
        metrics.average_compatibility_score = std::accumulate(compatibility_scores.begin(),
                                                            compatibility_scores.end(), 0.0) /
                                            compatibility_scores.size();
    }

    metrics.license_types = calculateLicenseDistribution(dependencies);
    metrics.source_types = calculateSourceDistribution(dependencies);
    metrics.status_distribution = calculateStatusDistribution(dependencies);

    return metrics;
}

std::vector<DependencyTrend> DependencyReporter::analyzeDependencyTrends(const std::vector<DependencySnapshot>& snapshots) const {
    std::vector<DependencyTrend> trends;

    if (snapshots.size() < 2) {
        return trends;
    }

    // Analyze numeric trends
    trends = analyzeNumericTrends(snapshots);

    // Analyze categorical trends
    auto categorical_trends = analyzeCategoricalTrends(snapshots);
    trends.insert(trends.end(), categorical_trends.begin(), categorical_trends.end());

    return trends;
}

std::vector<std::string> DependencyReporter::generateRecommendations(const std::vector<DependencyInfo>& dependencies) const {
    std::vector<std::string> recommendations;

    int outdated_count = 0;
    int security_issues_count = 0;
    int low_compatibility_count = 0;

    for (const auto& dep : dependencies) {
        if (dep.status == "outdated") {
            outdated_count++;
            if (!dep.available_version.empty()) {
                recommendations.push_back("Update " + dep.name + " from " + dep.version +
                                        " to " + dep.available_version);
            }
        }

        if (!dep.security_issues.empty()) {
            security_issues_count++;
        }

        if (dep.compatibility_score > 0 && dep.compatibility_score < 70) {
            low_compatibility_count++;
        }
    }

    // General recommendations
    if (outdated_count > 0) {
        recommendations.push_back("Review and update " + std::to_string(outdated_count) +
                                " outdated dependencies");
    }

    if (security_issues_count > 0) {
        recommendations.push_back("Address " + std::to_string(security_issues_count) +
                                " security issues across dependencies");
    }

    if (low_compatibility_count > 0) {
        recommendations.push_back("Investigate " + std::to_string(low_compatibility_count) +
                                " dependencies with low compatibility scores");
    }

    if (recommendations.empty()) {
        recommendations.push_back("All dependencies are up-to-date and compatible");
    }

    return recommendations;
}

std::vector<std::string> DependencyReporter::identifySecurityIssues(const std::vector<DependencyInfo>& dependencies) const {
    std::vector<std::string> security_issues;

    for (const auto& dep : dependencies) {
        if (!dep.security_issues.empty()) {
            for (const auto& issue : dep.security_issues) {
                security_issues.push_back(dep.name + ": " + issue);
            }
        }
    }

    return security_issues;
}

DependencyDocumentation DependencyReporter::generateDependencyDocumentation(const std::vector<DependencyInfo>& dependencies) const {
    DependencyDocumentation docs;
    docs.doc_id = generateReportID();
    docs.generated_timestamp = getCurrentTimestamp();
    docs.version = getReportVersion();
    docs.format = "markdown";

    std::ostringstream content;

    content << "# Dependency Documentation\n\n";
    content << "## Overview\n\n";
    content << "This document provides comprehensive information about all dependencies used in this project.\n\n";

    // Summary
    auto metrics = generateDependencyMetrics(dependencies);
    content << "### Summary\n\n";
    content << "- **Total Dependencies:** " << metrics.total_dependencies << "\n";
    content << "- **Active Dependencies:** " << metrics.active_dependencies << "\n";
    content << "- **Outdated Dependencies:** " << metrics.outdated_dependencies << "\n";
    content << "- **Average Compatibility Score:** " << formatCompatibilityScore(metrics.average_compatibility_score) << "\n\n";

    // Library Details
    content << "## Library Details\n\n";
    for (const auto& dep : dependencies) {
        content << "### " << dep.name << "\n\n";
        content << "**Version:** " << dep.version << "\n";
        content << "**Status:** " << dep.status << "\n";
        content << "**License:** " << dep.license << "\n";
        content << "**Source Type:** " << dep.source_type << "\n";

        if (!dep.description.empty()) {
            content << "**Description:** " << dep.description << "\n";
        }

        if (!dep.url.empty()) {
            content << "**URL:** " << dep.url << "\n";
        }

        if (!dep.sha256.empty()) {
            content << "**SHA256:** " << dep.sha256 << "\n";
        }

        if (dep.compatibility_score > 0) {
            content << "**Compatibility Score:** " << formatCompatibilityScore(dep.compatibility_score) << "\n";
        }

        content << "\n";
    }

    // Integration Guide
    content << generateIntegrationGuide(dependencies);

    // Maintenance Guide
    content << generateMaintenanceGuide(dependencies);

    docs.content = content.str();

    // Generate sections list
    docs.sections = {"Overview", "Summary", "Library Details", "Integration Guide", "Maintenance Guide"};

    return docs;
}

std::string DependencyReporter::generateIntegrationGuide(const std::vector<DependencyInfo>& dependencies) const {
    std::ostringstream guide;

    guide << "## Integration Guide\n\n";
    guide << "This section provides guidance on how to integrate and use the dependencies.\n\n";

    // CMake integration
    guide << "### CMake Integration\n\n";
    guide << "Dependencies are integrated using CMake FetchContent or CMake find_package.\n\n";
    guide << "```cmake\n";
    guide << "# Example of adding dependencies in CMakeLists.txt\n";
    guide << "include(FetchContent)\n\n";

    for (const auto& dep : dependencies) {
        if (dep.source_type == "cmake_fetch") {
            guide << "# FetchContent_Declare(\n";
            guide << "#   " << dep.name << "\n";
            guide << "#   URL \"" << dep.url << "\"\n";
            guide << "#   URL_HASH SHA256=" << dep.sha256 << "\n";
            guide << "# )\n";
            guide << "# FetchContent_MakeAvailable(" << dep.name << ")\n\n";
        }
    }
    guide << "```\n\n";

    // Include headers
    guide << "### Header Includes\n\n";
    guide << "Include necessary headers in your source files:\n\n";
    guide << "```cpp\n";
    for (const auto& dep : dependencies) {
        if (dep.name == "nlohmann_json") {
            guide << "#include <nlohmann/json.hpp>\n";
        } else if (dep.name == "googletest") {
            guide << "#include <gtest/gtest.h>\n";
        }
    }
    guide << "```\n\n";

    return guide.str();
}

std::string DependencyReporter::generateMaintenanceGuide(const std::vector<DependencyInfo>& dependencies) const {
    std::ostringstream guide;

    guide << "## Maintenance\n\n";
    guide << "This section provides guidance on maintaining dependencies.\n\n";

    // Update procedures
    guide << "### Update Procedures\n\n";
    guide << "1. **Check for updates regularly** using the dependency management scripts.\n";
    guide << "2. **Test compatibility** before updating to new versions.\n";
    guide << "3. **Update one dependency at a time** to isolate issues.\n";
    guide << "4. **Review changelogs** for breaking changes.\n";
    guide << "5. **Run tests** after each update.\n\n";

    // Security monitoring
    guide << "### Security Monitoring\n\n";
    guide << "1. **Monitor security advisories** for all dependencies.\n";
    guide << "2. **Update immediately** when security patches are available.\n";
    guide << "3. **Review dependency trees** for transitive security issues.\n";
    guide << "4. **Use vulnerability scanning tools** regularly.\n\n";

    // License compliance
    guide << "### License Compliance\n\n";
    guide << "1. **Track all licenses** used in the project.\n";
    guide << "2. **Ensure compliance** with license requirements.\n";
    guide << "3. **Document license information** clearly.\n";
    guide << "4. **Review license changes** when updating dependencies.\n\n";

    return guide.str();
}

std::string DependencyReporter::generateTroubleshootingGuide(const std::vector<DependencyInfo>& dependencies) const {
    std::ostringstream guide;

    guide << "## Troubleshooting\n\n";
    guide << "This section provides solutions to common dependency-related issues.\n\n";

    guide << "### Common Issues\n\n";
    guide << "1. **Build Failures**\n";
    guide << "   - Check if all dependencies are properly configured\n";
    guide << "   - Verify CMake configuration is correct\n";
    guide << "   - Ensure all required dependencies are available\n\n";

    guide << "2. **Version Conflicts**\n";
    guide << "   - Use the conflict detection tools provided\n";
    guide << "   - Check dependency compatibility matrix\n";
    guide << "   - Update to compatible versions when possible\n\n";

    guide << "3. **License Issues**\n";
    guide << "   - Review license compatibility\n";
    guide << "   - Ensure proper attribution is included\n";
    guide << "   - Document all license usage\n\n";

    return guide.str();
}

bool DependencyReporter::exportReportToFile(const std::vector<DependencyInfo>& dependencies,
                                          const std::string& file_path,
                                          const std::string& format) const {
    ExportOptions options;
    options.format = format;
    options.output_path = file_path;
    options.include_metadata = include_metadata_;
    options.include_trends = include_trends_;
    options.include_recommendations = include_recommendations_;

    return exportReportWithOptions(dependencies, options);
}

bool DependencyReporter::exportReportWithOptions(const std::vector<DependencyInfo>& dependencies,
                                                const ExportOptions& options) const {
    if (!validateExportOptions(options)) {
        return false;
    }

    std::string content;

    if (options.format == "json") {
        content = generateJSONReport(dependencies).dump(4);
    } else if (options.format == "markdown") {
        content = generateMarkdownReport(dependencies);
    } else if (options.format == "html") {
        content = generateHTMLReport(dependencies);
    } else if (options.format == "csv") {
        content = generateCSVReport(dependencies);
    } else if (!options.template_id.empty()) {
        auto it = report_templates_.find(options.template_id);
        if (it != report_templates_.end()) {
            content = generateCustomReport(dependencies, it->second);
        } else {
            return false;
        }
    } else {
        return false;
    }

    return writeToFile(content, options.output_path);
}

std::vector<std::string> DependencyReporter::getSupportedFormats() const {
    return {"json", "markdown", "html", "csv"};
}

// Template system implementation
bool DependencyReporter::loadTemplate(const std::string& template_id, const std::string& template_content) {
    if (!validateTemplate(template_content)) {
        return false;
    }

    report_templates_[template_id] = template_content;
    return true;
}

bool DependencyReporter::saveTemplate(const std::string& template_id, const ReportTemplate& template_info) {
    if (!validateTemplate(template_info.template_content)) {
        return false;
    }

    report_templates_[template_id] = template_info.template_content;

    // Save to file
    std::string template_file = cache_dir_ + "/templates/" + template_id + ".template";
    return writeToFile(template_info.template_content, template_file);
}

std::string DependencyReporter::generateCustomReport(const std::vector<DependencyInfo>& dependencies,
                                                    const std::string& template_content) const {
    auto report = generateDependencyReport(dependencies);
    return renderTemplate(template_content, dependencies, report);
}

// Filtering and sorting implementation
std::vector<DependencyInfo> DependencyReporter::filterDependencies(const std::vector<DependencyInfo>& dependencies,
                                                                  const std::string& field,
                                                                  const std::string& value) const {
    std::vector<DependencyInfo> filtered;

    for (const auto& dep : dependencies) {
        if (field == "name" && dep.name == value) {
            filtered.push_back(dep);
        } else if (field == "status" && dep.status == value) {
            filtered.push_back(dep);
        } else if (field == "license" && dep.license == value) {
            filtered.push_back(dep);
        } else if (field == "source_type" && dep.source_type == value) {
            filtered.push_back(dep);
        }
    }

    return filtered;
}

std::vector<DependencyInfo> DependencyReporter::sortDependencies(const std::vector<DependencyInfo>& dependencies,
                                                                const std::string& field,
                                                                bool ascending) const {
    auto sorted = dependencies;

    std::sort(sorted.begin(), sorted.end(),
        [field, ascending](const DependencyInfo& a, const DependencyInfo& b) {
            if (field == "name") {
                return ascending ? a.name < b.name : a.name > b.name;
            } else if (field == "version") {
                return ascending ? a.version < b.version : a.version > b.version;
            } else if (field == "status") {
                return ascending ? a.status < b.status : a.status > b.status;
            } else if (field == "compatibility_score") {
                return ascending ? a.compatibility_score < b.compatibility_score :
                                 a.compatibility_score > b.compatibility_score;
            }
            return false;
        });

    return sorted;
}

std::vector<DependencyInfo> DependencyReporter::searchDependencies(const std::vector<DependencyInfo>& dependencies,
                                                                  const std::string& query) const {
    std::vector<DependencyInfo> results;
    std::string lower_query = query;
    std::transform(lower_query.begin(), lower_query.end(), lower_query.begin(), ::tolower);

    for (const auto& dep : dependencies) {
        std::string lower_name = dep.name;
        std::string lower_desc = dep.description;
        std::transform(lower_name.begin(), lower_name.end(), lower_name.begin(), ::tolower);
        std::transform(lower_desc.begin(), lower_desc.end(), lower_desc.begin(), ::tolower);

        if (lower_name.find(lower_query) != std::string::npos ||
            lower_desc.find(lower_query) != std::string::npos) {
            results.push_back(dep);
        }
    }

    return results;
}

// Private helper function implementations
bool DependencyReporter::loadDefaultTemplates() {
    // Load default templates for different formats
    std::string html_template = generateHTMLHeader("Dependency Report");
    html_template += "{{content}}";
    html_template += generateHTMLFooter();
    report_templates_["default_html"] = html_template;

    std::string markdown_template = R"(
# Dependency Report: {{report_id}}
Generated: {{generated_timestamp}}

## Summary
- Total Dependencies: {{total_dependencies}}
- Active Dependencies: {{active_dependencies}}
- Outdated Dependencies: {{outdated_dependencies}}

## Dependencies
{{#dependencies}}
### {{name}}
- Version: {{version}}
- Status: {{status}}
- License: {{license}}
{{/dependencies}}
)";
    report_templates_["default_markdown"] = markdown_template;

    return true;
}

std::string DependencyReporter::generateReportID() const {
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_int_distribution<> dis(100000, 999999);

    auto now = std::chrono::system_clock::now();
    auto time_t = std::chrono::system_clock::to_time_t(now);

    std::ostringstream oss;
    oss << "RPT-" << std::put_time(std::gmtime(&time_t), "%Y%m%d")
        << "-" << std::setw(6) << std::setfill('0') << dis(gen);

    return oss.str();
}

std::string DependencyReporter::getCurrentTimestamp() const {
    auto now = std::chrono::system_clock::now();
    auto time_t = std::chrono::system_clock::to_time_t(now);

    std::ostringstream oss;
    oss << std::put_time(std::gmtime(&time_t), "%Y-%m-%dT%H:%M:%SZ");

    return oss.str();
}

std::string DependencyReporter::formatCompatibilityScore(double score) const {
    std::ostringstream oss;
    oss << std::fixed << std::setprecision(1) << score << "%";
    return oss.str();
}

std::string DependencyReporter::generateHTMLHeader(const std::string& title) const {
    std::ostringstream header;
    header << "<!DOCTYPE html>\n";
    header << "<html lang=\"en\">\n";
    header << "<head>\n";
    header << "    <meta charset=\"UTF-8\">\n";
    header << "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
    header << "    <title>" << escapeHTML(title) << "</title>\n";
    header << "    <style>\n";
    header << generateCSSStyles();
    header << "    </style>\n";
    header << "</head>\n";
    return header.str();
}

std::string DependencyReporter::generateHTMLFooter() const {
    return "</html>\n";
}

std::string DependencyReporter::generateCSSStyles() const {
    return R"(
body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
.container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #eee; padding-bottom: 20px; }
h1 { color: #333; margin-bottom: 10px; }
.report-info { color: #666; font-size: 14px; }
.stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 30px 0; }
.stat-card { background: #f8f9fa; padding: 20px; border-radius: 8px; text-align: center; border-left: 4px solid #007bff; }
.stat-card h3 { margin: 0; font-size: 2em; color: #007bff; }
.stat-card p { margin: 5px 0 0 0; color: #666; }
.dependency-table { width: 100%; border-collapse: collapse; margin: 20px 0; }
.dependency-table th, .dependency-table td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
.dependency-table th { background-color: #f8f9fa; font-weight: 600; }
.status-active { color: #28a745; font-weight: 600; }
.status-outdated { color: #ffc107; font-weight: 600; }
.status-unknown { color: #6c757d; }
.recommendations { margin: 30px 0; }
.recommendations-list { background: #e7f3ff; padding: 20px; border-radius: 8px; border-left: 4px solid #007bff; }
.recommendations-list li { margin: 10px 0; }
section { margin: 40px 0; }
h2 { color: #333; border-bottom: 2px solid #eee; padding-bottom: 10px; }
)";
}

std::string DependencyReporter::escapeHTML(const std::string& text) const {
    std::string escaped = text;
    std::regex special_chars {"&|<|>|\"|'"};

    escaped = std::regex_replace(escaped, std::regex("&"), "&amp;");
    escaped = std::regex_replace(escaped, std::regex("<"), "&lt;");
    escaped = std::regex_replace(escaped, std::regex(">"), "&gt;");
    escaped = std::regex_replace(escaped, std::regex("\""), "&quot;");
    escaped = std::regex_replace(escaped, std::regex("'"), "&#39;");

    return escaped;
}

bool DependencyReporter::writeToFile(const std::string& content, const std::string& file_path) const {
    std::ofstream file(file_path);
    if (!file.is_open()) {
        return false;
    }

    file << content;
    return file.good();
}

bool DependencyReporter::ensureDirectoryExists(const std::string& dir_path) const {
    return fs::create_directories(dir_path);
}

json DependencyReporter::dependencyToJSON(const DependencyInfo& dep) const {
    json json_dep;
    json_dep["name"] = dep.name;
    json_dep["version"] = dep.version;
    json_dep["source_type"] = dep.source_type;
    json_dep["license"] = dep.license;
    json_dep["status"] = dep.status;
    json_dep["metadata"] = dep.metadata;
    json_dep["dependencies"] = dep.dependencies;
    json_dep["conflicts_with"] = dep.conflicts_with;
    json_dep["description"] = dep.description;
    json_dep["url"] = dep.url;
    json_dep["sha256"] = dep.sha256;
    json_dep["extracted_date"] = dep.extracted_date;
    json_dep["last_update"] = dep.last_update;
    json_dep["compatibility_score"] = dep.compatibility_score;
    json_dep["available_version"] = dep.available_version;
    json_dep["security_issues"] = dep.security_issues;

    return json_dep;
}

std::map<std::string, int> DependencyReporter::calculateLicenseDistribution(const std::vector<DependencyInfo>& dependencies) const {
    std::map<std::string, int> distribution;

    for (const auto& dep : dependencies) {
        if (!dep.license.empty()) {
            distribution[dep.license]++;
        }
    }

    return distribution;
}

std::map<std::string, int> DependencyReporter::calculateSourceDistribution(const std::vector<DependencyInfo>& dependencies) const {
    std::map<std::string, int> distribution;

    for (const auto& dep : dependencies) {
        if (!dep.source_type.empty()) {
            distribution[dep.source_type]++;
        }
    }

    return distribution;
}

std::map<std::string, int> DependencyReporter::calculateStatusDistribution(const std::vector<DependencyInfo>& dependencies) const {
    std::map<std::string, int> distribution;

    for (const auto& dep : dependencies) {
        if (!dep.status.empty()) {
            distribution[dep.status]++;
        }
    }

    return distribution;
}

bool DependencyReporter::validateDependencies(const std::vector<DependencyInfo>& dependencies) const {
    for (const auto& dep : dependencies) {
        if (dep.name.empty() || dep.version.empty()) {
            return false;
        }
    }
    return true;
}

bool DependencyReporter::validateTemplate(const std::string& template_content) const {
    return !template_content.empty();
}

bool DependencyReporter::validateExportOptions(const ExportOptions& options) const {
    if (options.format.empty() || options.output_path.empty()) {
        return false;
    }

    std::vector<std::string> supported_formats = getSupportedFormats();
    return std::find(supported_formats.begin(), supported_formats.end(), options.format) !=
           supported_formats.end();
}

std::string DependencyReporter::renderTemplate(const std::string& template_content,
                                              const std::vector<DependencyInfo>& dependencies,
                                              const DependencyReport& report) const {
    std::string rendered = template_content;

    // Replace simple variables
    std::map<std::string, std::string> variables = {
        {"report_id", report.report_id},
        {"generated_timestamp", report.generated_timestamp},
        {"total_dependencies", std::to_string(report.total_dependencies)},
        {"active_dependencies", std::to_string(report.active_dependencies)},
        {"outdated_dependencies", std::to_string(report.outdated_dependencies)},
        {"content", "Generated report content"}
    };

    rendered = replaceTemplateVariables(rendered, variables);

    return rendered;
}

std::string DependencyReporter::replaceTemplateVariables(const std::string& content,
                                                        const std::map<std::string, std::string>& variables) const {
    std::string result = content;

    for (const auto& [key, value] : variables) {
        std::string placeholder = "{{" + key + "}}";
        size_t pos = result.find(placeholder);
        while (pos != std::string::npos) {
            result.replace(pos, placeholder.length(), value);
            pos = result.find(placeholder, pos + value.length());
        }
    }

    return result;
}

std::vector<DependencyTrend> DependencyReporter::analyzeNumericTrends(const std::vector<DependencySnapshot>& snapshots) const {
    std::vector<DependencyTrend> trends;

    if (snapshots.size() < 2) return trends;

    // Analyze total dependencies trend
    DependencyTrend total_trend;
    total_trend.metric_name = "total_dependencies";
    total_trend.data_points.resize(snapshots.size());

    for (size_t i = 0; i < snapshots.size(); ++i) {
        total_trend.data_points[i] = static_cast<double>(snapshots[i].total_dependencies);
    }

    double slope = calculateTrendSlope(total_trend.data_points);
    total_trend.change_value = slope;
    total_trend.trend_direction = slope > 0.1 ? "increasing" :
                                  slope < -0.1 ? "decreasing" : "stable";

    trends.push_back(total_trend);

    return trends;
}

std::vector<DependencyTrend> DependencyReporter::analyzeCategoricalTrends(const std::vector<DependencySnapshot>& snapshots) const {
    std::vector<DependencyTrend> trends;
    // Implementation for categorical trend analysis
    return trends;
}

double DependencyReporter::calculateTrendSlope(const std::vector<double>& values) const {
    if (values.size() < 2) return 0.0;

    // Simple linear regression to calculate trend
    double n = static_cast<double>(values.size());
    double sum_x = 0.0, sum_y = 0.0, sum_xy = 0.0, sum_x2 = 0.0;

    for (size_t i = 0; i < values.size(); ++i) {
        double x = static_cast<double>(i);
        double y = values[i];
        sum_x += x;
        sum_y += y;
        sum_xy += x * y;
        sum_x2 += x * x;
    }

    return (n * sum_xy - sum_x * sum_y) / (n * sum_x2 - sum_x * sum_x);
}

} // namespace integration